class StyleAttribute {
  String? fontStyle;
  String? fontWeight;
  String? fontSize;
  String? color;
  String? background;
  String? backgroundColor;
  String? textDecorationLine;
  String? textDecorationStyle;
  String? textDecorationColor;
  String? borderColor;
  String? borderStyle;
  String? borderRadius;
  String? borderWidth;
  String? clipPath;
  String? verticalAlign;
  String? textAlign;
  String? textEmphasis;
  String? textShadow;
  String? margin;
  String? marginTop;
  String? marginLeft;
  String? marginRight;
  String? marginBottom;
  String? padding;
  String? paddingTop;
  String? paddingLeft;
  String? paddingRight;
  String? paddingBottom;
  String? wordBreak;
  String? whiteSpace;
  String? cursor;
  String? listStyleType;
  String extra = '';
}
